# Site settings
title: The PeARS project
email: aurelie DOT herbelot AT cantab DOT net
description: "PeARS (Peer-to-peer Agent for Reciprocated Search) is a running experiment on whether the work of traditional search engines can be done in a distributed fashion. The project is developed for the Raspberry Pi."
baseurl: /PeARS
url: "http://www.cl.cam.ac.uk/~ah433/"
twitter_username: none
github_username:  minimalparts
pygments: true

# Build settings
markdown: kramdown
permalink: pretty
