# Site settings
title: The PeARS project
email: aurelie DOT herbelot AT cantab DOT net
description: "PeARS (Peer-to-peer Agent for Reciprocated Search) is a basic prototype for a distributed search engine. The project focuses on a) the integration of deep(er) linguistic knowledge in theframework b) a flexible system that affords both increased privacy and social networking capabilities. It is being developed for the raspberry pi."
baseurl: /PeARS
url: "http://www.cl.cam.ac.uk/~ah433/"
twitter_username: PeARSsearch
github_username:  minimalparts
pygments: true

# Build settings
markdown: kramdown
permalink: pretty
